### ISSUE TITLE
About the shadow detection results on SBU 

### ISSUE THREAD

**Issue by guanhuankang** [eraserNut/MTMT#12]
Hi, I try to do some test on your SBU results, but I encountered a problem that the images' name is renamed with 1~638(eg: 1.png). And I can't find a mapping relationship between the index and the original file name, which means that we can't compare your results with the groundtruth. Could you provide a SBU results, which named in the original file name, again please? I am waiting for you early reply! Thanks a lot!

**Comment by guanhuankang** [comment]
I have solved my problems. Thanks! [The SBU dataset shared by you contain a copy, which have been renamed. I will close this issue. Thanks again]

**Comment by eraserNut** [comment]
Fine, thank you for your attention to our work!
