### ISSUE TITLE
Question about UCF dataset

### ISSUE THREAD

**Issue by cvbird** [eraserNut/MTMT#28]
Hi, there. Thank you for this project. I got a question about UCF dataset. As mentioned in your paper in section 4.1 that "The UCF dataset consists of 145 training images and 76 testing images, covering outdoor scenes;", If I understood correctly, the number of testing images should be 76. However, in the UCF dataset provided, it contains 110 images which is inconsistent with 76. I also checked other paper and found most works' provided UCF detection results had 76 images either. I don't know where is the problem. Thank you very much.

**Comment by eraserNut** [comment]
There are some problems with the description in our paper. Actually, UCF has not released its dataset. We ask the author for their dataset and obtain those 110 images. So we see those 110 images as UCF.

**Comment by eraserNut** [comment]
In some works, UCF has 76 images, which is not the real UCF. I asked some authors that use this setting and they also say this is a historical question and 76 is not a real UCF.

**Comment by cvbird** [comment]
> In some works, UCF has 76 images, which is not the real UCF. I asked some authors that use this setting and they also say this is a historical question and 76 is not a real UCF.

OK, I see.
Thank you very much!
