### ISSUE TITLE
There are some bugs

### ISSUE THREAD

**Issue by cqwly** [eraserNut/MTMT#33]
Hi, thanks for your work and code. There are some bugs when I runing your code.
1. **AttributeError: 'SBU' object has no attribute 'multi_task'**
in train.py: db_train = SBU(root=train_data_path, joint_transform=joint_transform, transform=img_transform, target_transform=target_transform, mod='union', multi_task=True, edge=True) 
however, in SBU.py: def __init__(self, root, joint_transform=None, transform=None, target_transform=None, mod='union', subitizing=False, subitizing_threshold=8, subitizing_min_size_per=0.005, edge=False):

2. **TypeError: __call__() takes 3 positional arguments but 4 were given in SBU.py at line 108**
img, target, edge = self.joint_transform(img, target, edge)
however, in joint_transform.py, it is defined as:
def __call__(self, img, mask):
        assert img.size == mask.size
        for t in self.transforms:
            img, mask = t(img, mask)
        return img, mask

**Comment by baoxianjian** [comment]
1. You can add this property to SBU class by your self by changing MTMT/dataloaders/SBU.py, like this:
class SBU(data.Dataset):
    def __init__(self, ......, multi_task=False):
        ......
        self.multi_task = multi_task

2. Using joint_transforms_edge instead may sovle you problem by changing MTMT/train.py, like this:
from dataloaders import joint_transforms_edge as joint_transforms

**Comment by cqwly** [comment]
> 1. You can add this property to SBU class by your self by changing MTMT/dataloaders/SBU.py, like this:
>    class SBU(data.Dataset):
>    def **init**(self, ......, multi_task=False):
>    ......
>    self.multi_task = multi_task
> 2. Using joint_transforms_edge instead may sovle you problem by changing MTMT/train.py, like this:
>    from dataloaders import joint_transforms_edge as joint_transforms
Hi, thanks for your reply! I solved these problems just as what you suggested.
