### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by devsergioraar** [eraserNut/MTMT#39]
Hello

How are you?

I write asking for help. I have been struggling to run the test.

I do not know where is this file "iter_10000.pth":

snapshot_path = '../model_SBU_EGNet/baselineC64_DSS_unlabelcons/repeat16_edge10.0lr0.005consistency1.0subitizing5.0/iter_10000.pth' 

May you help me get the file?
Or how to do this test runnable?

I have download SBU, UCF datasets.
I have download Resnet.

Thanks in advance!

**Comment by eraserNut** [comment]
The pre-trained model can be obtained in the "trained model" section.
Now it was uploaded to BaiduDisk.
Tonight, I will upload it to google drive for your convenience.

**Comment by eraserNut** [comment]
https://drive.google.com/file/d/1s-4BSmz9j8u2_WoUnzNYL0QjRYFEeEkU/view?usp=share_link

**Comment by devsergioraar** [comment]
Thank you.

I appreciate this help.
