### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by chiukin** [eraserNut/MTMT#4]
1. 文中说 'we re-train our method and most competitors on the ISTD training dataset with our unlabeled data.'  那在训练ISTD时，你们的模型没用到未标注的数据来训练，这只能训练student network吧？或是你们是用了未标注的数据，但其他方法就没用是吧。
2. 还有就是想问下student network和teacher network的结构是否完全一样？

**Comment by eraserNut** [comment]
1. 我文中这句话的描述有欠缺，因为对比方法无法使用未标注的数据，所以这批数据只用于我们提出的方法。另，只训练student network的部分在退化实验中有描述。
2.结构完全一样，这是由于mean-teacher的参数更新策略的天然限制。

**Comment by chiukin** [comment]
嗯，再想问下，mean techer和知识蒸馏有什么区别没，知识蒸馏也有student和teacher，不过teacher的网络好像比student的大。mean techer和知识蒸馏两个的作用是否相同

**Comment by eraserNut** [comment]
有一定的区别，知识蒸馏的目的是让student学习到近似teacher的性能，最后用来进行模型压缩，正常来说student是不会超过teacher的。但是在mean-teacher中，虽然也用了相同的名词，但是这里的teacher其实保留的是student的历史预测结果，更像是一种正则化方式。而且在这种框架中，student的结果往往会比teacher要高一些。
